# Setup
title:        ISBERTO.org
tagline:      We all came from one Family Tree
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Luigi
  url:        https://www.facebook.com/luigi.isberto 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
