# Setup
title:        ISBERTO.org
tagline:      We all came from one Family Tree
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Luigi
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
