# Setup
title:        ISBERTO.org
tagline:      Like branches on a tree, we grow in different directions, yet our roots remain as one....
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Luigi Isberto
  url:        https://www.facebook.com/luigi.isberto 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
